title: CS Notes
description: >- # this means to ignore newlines until "baseurl:"
  Notes from learning computer science.
baseurl: ""
url: https://itsalexousd.github.io/

markdown: kramdown
theme: just-the-docs
plugins:
  - jekyll/scholar

aux_links:
  "view on GitHub":
    - "//github.com/itsalexousd/notes"

scholar:
  style: _bibliography/custom
  source: _bibliography

exclude:
  - Gemfile
  - Gemfile.lock
