# Site setting
title: CS Notes
description: Notes from learning computer science.
url: https://itsalexousd.github.io
twitter_username: itsalexousd
github_username: itsalexousd
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
search: true

# Build settings
remote_theme: just-the-docs/just-the-docs
markdown: kramdown

aux_links:
  "View on GitHub":
    - "//github.com/itsalexousd/notes"
aux_links_new_tab: true

plugins:
  - jekyll/scholar

author:
  name: "Alexis Dalle"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/itsalexousd"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alexis-dalle/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/itsalexousd"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/itsalexousd"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/alexis-dalle/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/itsalexousd"

scholar:
  style: _bibliography/custom
  source: _bibliography
